apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-1
  namespace: resources-review
  labels:
    app: hw-app-1
    kuma.io/service: hw-app-1 # Etiqueta para Kuma
  annotations:
    kuma.io/sidecar-injection: "enabled"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-1
  template:
    metadata:
      labels:
        app: hw-app-1
        kuma.io/service: hw-app-1 # Etiqueta para Kuma
    spec:
      containers:
      - name: hw-container-app-1
        image: jaimehenao8126/poc-app-1:d747e8cb56cfdf56b72094b4e9c1a79a3d2069ca
        ports:
        - containerPort: 80
