apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-1
  template:
    metadata:
      labels:
        app: hw-app-1
    spec:
      containers:
      - name: hw-container-app-1
        image: jaimehenao8126/poc-app-1:f121e825f687c5c9f8772b268d820b913a9ec1fa
        ports:
        - containerPort: 80
