apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-1
  template:
    metadata:
      labels:
        app: hw-app-1
    spec:
      containers:
      - name: hw-container-app-1
        image: jaimehenao8126/poc-app-1:7df50cbe8d9653798bf25cf99d3a065768893626
        ports:
        - containerPort: 80
