apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy-app-1
spec:
  replicas: 1  # Ajusta el número de replicas según tus necesidades
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-app-1
  template:
    metadata:
      labels:
        app: hw-app-1
    spec:
      containers:
      - name: hw-container-app-1
        image: jaimehenao8126/kantox:233afb52f68b755546bba253dd198c1d2c40409a
        ports:
        - containerPort: 80
