apiVersion: v1
kind: Service
metadata:
  name: hw-service-app-1
  labels:
    app: hw-app-1
    kuma.io/service: hw-app-1 # Etiqueta para Kuma
spec:
  selector:
    app: hw-app-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30795
  type: NodePort
